CREATE TABLE `reservations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reservationId` varchar(64) NOT NULL,
	`customerId` varchar(64),
	`facilityId` varchar(64) NOT NULL,
	`customerName` varchar(100) NOT NULL,
	`customerPhone` varchar(20) NOT NULL,
	`customerEmail` varchar(320),
	`firstChoiceDate` timestamp NOT NULL,
	`firstChoiceTimeSlot` varchar(50) NOT NULL,
	`secondChoiceDate` timestamp,
	`secondChoiceTimeSlot` varchar(50),
	`thirdChoiceDate` timestamp,
	`thirdChoiceTimeSlot` varchar(50),
	`confirmedDate` timestamp,
	`confirmedTimeSlot` varchar(50),
	`status` enum('pending','confirmed','completed','cancelled','no_show') NOT NULL DEFAULT 'pending',
	`notes` varchar(1000),
	`staffNotes` varchar(1000),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reservations_id` PRIMARY KEY(`id`),
	CONSTRAINT `reservations_reservationId_unique` UNIQUE(`reservationId`)
);
