CREATE TABLE `questionnaires` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerId` int,
	`customerUuid` varchar(64),
	`visitDate` varchar(20),
	`mainConcern` text,
	`symptoms` text,
	`symptomsOther` varchar(200),
	`symptomsMemo` text,
	`inconveniences` text,
	`inconveniencesOther` varchar(200),
	`inconveniencesMemo` text,
	`attitude` varchar(200),
	`treatmentPrefs` text,
	`pastIllness` varchar(300),
	`pastInjury` varchar(300),
	`pastOther` varchar(300),
	`pastClinic` text,
	`pastClinicOther` varchar(200),
	`pregnancyStatus` varchar(100),
	`pregnancyMonths` int,
	`snsPermission` varchar(50),
	`preferredDays` text,
	`preferredTimes` text,
	`referralSource` text,
	`referralName` varchar(100),
	`referralOther` varchar(200),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `questionnaires_id` PRIMARY KEY(`id`)
);
